_commit: local-example
_src_path: https://github.com/Matgenix/datalab-tool-plugin-template
author_email: dev@datalab-org.io
author_name: datalab development team
description: A standalone Hello World tool for datalab
distribution_name: datalab-hello-standalone-tool
tool_id: hello-standalone
tool_name: Hello standalone
tool_ui_kind: standalone
tool_open_mode: new_tab
